/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f1xx_hal.h"
#include "motorctrl/motorctrl.h"
#include "inboardio/inboardio.h"
#include "exio/exio.h"
#include "at24cxx/at24cxx.h"
#include "storage/storage.h"
#include "delay/delay.h"
#include "tim5/tim5.h"
#include "led/led.h"
#include "dwin/gui.h"
#include "usart2/usart2.h"
#include "queue/queue.h"
#include "paramanager/paramanager.h"
#include "userfunc/userfunc.h"
#include "inputscan/inputscan.h"
//#include "iwdg/iwdg.h"

void task(void);
void IO_trigger(void);


int main(void)
{
	SystemCoreClockUpdate();

	delay_ms(1500);

	HAL_NVIC_SetPriorityGrouping(NVIC_PRIORITYGROUP_2);

	MC_config();
	STORAGE_init();

	IBIO_config();
	EXIO_config();

	LED_config();

	QUEUE_init(&recvQueue);
	QUEUE_init(&sendQueue);

	USART2_config();

	GUI_initDisplay();

	GUI_switchPageIsolate(32);

	TIM5_config();

	//IWDG_config();

	EXIO_enableEXI0Interrupt(); //使能中断

	MC_motorStopAllEmergency();

	GUI_showText(0x8000, "        ", 8);
	GUI_showText(0x8000, "0", 1);
	GUI_showTextIsolate(MAINPAGE_MESSAGE_ADDR,MAINPAGE_MESAGE_CLEAR);
	systemPara.RunStatus = 0;
	systemPara.Initstatus = 0;
	systemPara.LackMaterral = 1;
	systemPara.Language = 0;

//	if(systemPara.status != STATUS_ONLINE)//不在工作模式下，输出报警
//		EXO_sigON(4);


	for(;;)
	{
		GUI_handler();

		GUI_sendTask(0);

		task();

		//IN_checkMetal();
	}
}

void task(void)
{
	static uint8_t stop_falg = 0;

	IO_trigger();
	StopModeIO(0);

	if(IBIO_getInput(12) == 0)//驱动器报警检测
	{
		delay_ms(5);
		if(IBIO_getInput(12) == 0)
		{
			MdriveALM();
		}
	}

	if(systemPara.isInEmergencyStopEnable)
	{
		if(IBIO_getInput(5) == 1)
		{
			stop_falg = 1;
			MAIN_TIPS_WAIT_RST_E_STOP();
			return;
		}
		else if(IBIO_getInput(5) == 0 && stop_falg == 1)
		{
			stop_falg = 0;
			MAIN_TIPS_RST_E_STOP();
			Clear();//清除所有的标志位
		}
	}
	

	ChuShiHua(0);

#ifndef CONF_GIVEN_MOTOR_TEST_ONLY
	flTask_handler(0);

	if(systemPara.isUpShouSensorEnable)
	{
		slUpTask_handler(0);
	}
#endif

	switch(systemPara.status)
	{
	case STATUS_ONLINE:
		
		if(systemPara.Initstatus == 1)
		{
			if(EXIO_getInput(3) == 1)
			{
				SL_Step_task(0);
#ifdef CONF_GIVEN_MOTOR_TEST_ONLY
				GoHome_step(0);
#else
				Shut_vacuum();
				CutLable_Step_level(0);
				RST_Step_task(0);
				Detect_vacuum();
#endif
			}
			else
			{
				MAIN_TIPS_EXI_E_STOP();
			}
		}
		break;
	case STATUS_AUTO:
		if(OLM_step != 0)
		{	systemPara.RunStatus = 0;
			OLM_step = 0;
		}
		if(systemPara.RSTOK == 2)
		{
			systemPara.RSTOK = 0;
			systemPara.givenOnceTriggerByUIorIO = 1;
		}
		SL_Step_task(0);
#ifdef CONF_GIVEN_MOTOR_TEST_ONLY
		GoHome_step(0);
#else
		CutLable_Step_RST(0);
		CutLable_Step_level(0);
		RST_Step_task(0);
		GoHome_step(0);
		GoHome_CutLable(0);
		Shut_vacuum();
#endif
		break;
	case STATUS_FREERUN:
#ifndef CONF_GIVEN_MOTOR_TEST_ONLY
		if(systemPara.Initstatus == 1)
		{
			KongPaoMoShi(0);
		}
#endif
		break;
	}

}

void IO_trigger(void)
{
	static uint8_t bSW1flag = 1,bSW2flag = 1,bSW3flag = 1,bSW4flag = 1,bSW5flag = 1;
	static uint8_t RstOK2song = 0;

	if(systemPara.isInEmergencyStopEnable)
	{
		if(IBIO_getInput(5) == 1 && bSW5flag == 1 )
		{//紧急停止触发
			delay_ms(2);
			if(IBIO_getInput(5) == 1)
			{
				bSW5flag = 0;
				systemPara.STOPOnceTriggerByUIorIO = 2;
			}
		}
		if(IBIO_getInput(5) == 0)
		{
			bSW5flag = 1;
		}
	}

	if(EXIO_getInput(2) == 0 && bSW3flag == 1 )
	{//初始化
		delay_ms(5);
		if(EXIO_getInput(2) == 0)
		{
			bSW3flag = 0;
			if(systemPara.isInitSwOnLINEEnable)
			{
				if(systemPara.status != STATUS_ONLINE)
				{
					MAIN_INFO_SW2ONLINE();
					systemPara.status = STATUS_ONLINE;
					AT24CXX_WriteOneByte(STORAGE_WORKMODE_ADDR, systemPara.status);
					GUI_switchModeDisp(systemPara.status);

				    if((IBIO_getInput(1) == 0 || systemPara.givenOK ==1)&& systemPara.Initstatus == 1)
				    {
						if(systemPara.Initstatus)
						{
							EXO_sigON(3);
							EXO_sigON(5);
							if(systemPara.givenOK)
								EXO_sigON(2);
						}
				    }
				}
			}

			if(systemPara.status != STATUS_ONLINE)
			{
				return;
			}
			if(systemPara.Err == 1)
			{
				systemPara.Err = 0;
				EXO_sigOFF(4);//清除报警信号
			}
			if(systemPara.Initstatus == 0)
			{
				EXO_sigOFF(4);//清除报警信号
				systemPara.doInit = 1;
			}
		}
	}
	if(EXIO_getInput(2) == 1)
	{
		bSW3flag = 1;
	}

	if(systemPara.status != STATUS_ONLINE)
		return;

	if(EXIO_getInput(3) == 0 && bSW4flag == 1 )
	{//停止触发
		delay_ms(5);
		if(EXIO_getInput(3) == 0)
		{
			bSW4flag = 0;
			systemPara.STOPOnceTriggerByUIorIO = 1;
		}
	}
	if(EXIO_getInput(3) == 1)
	{
		bSW4flag = 1;
	}

	if(systemPara.RunStatus != 0)
		return;
		


	if(systemPara.RunStatus != 0 || !systemPara.Initstatus)
		return;

	if(EXIO_getInput(0) == 0 && bSW1flag == 1)
	{//外部触发送料
		delay_ms(5);
		if(EXIO_getInput(0) == 0)
		{
			if(systemPara.CUTOK == 0)
			{
				bSW1flag = 0;
				if(IBIO_getInput(1) == 1)
				{
					systemPara.RSTOnceTriggerByUIorIO = 1;
					RstOK2song = 1;
				}
				else
					systemPara.givenOnceTriggerByUIorIO = 1;
			}
			else
			{
				if(systemPara.Language == 0)
					MAIN_TIPS_NO_CUT_FEED();
				else if(systemPara.Language == 1)
					EN_MAIN_TIPS_CUT_FEED();
			}
		}
	}

	if(RstOK2song && systemPara.RSTOK == 1)
	{//先复位再送料
		RstOK2song = 0;
		systemPara.givenOnceTriggerByUIorIO = 1;
	}

	if(EXIO_getInput(0) == 1)
	{
		RstOK2song = 0;
		bSW1flag = 1;
	}

	if(EXIO_getInput(1) == 0 && bSW2flag == 1 )
	{//关闭真空
		delay_ms(5);
		if(EXIO_getInput(1) == 0)
		{
			bSW2flag = 0;
			systemPara.Shutvacuum = 1;
		}
	}

	if(EXIO_getInput(1) == 1)
	{
		bSW2flag = 1;
	}
}



