/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f1xx_hal.h"
#include "motorctrl/motorctrl.h"
#include "inboardio/inboardio.h"
#include "exio/exio.h"
#include "at24cxx/at24cxx.h"
#include "storage/storage.h"
#include "delay/delay.h"
#include "tim5/tim5.h"
#include "led/led.h"
#include "dwin/gui.h"
#include "usart1/usart1.h"
#include "usart2/usart2.h"
#include "queue/queue.h"
#include "paramanager/paramanager.h"
#include "userfunc/userfunc.h"
#include "inputscan/inputscan.h"
#include "easymodbus/easymodbus.h"
//#include "iwdg/iwdg.h"

//例如：0x00 0x06 0x7919 0x0000 0xffff

uint8_t sendBuffer[34][8] ={
		{0x00, 0x03, 0x7d, 0x00, 0x00, 0x00, 0xff, 0xff  },//0清除停止状态
		{0x00, 0x03, 0x7d, 0x00, 0x00, 0x01, 0xff, 0xff  },//1停止状态

		{0x00, 0x03, 0x7d, 0x01, 0x00, 0x00, 0xff, 0xff  },//2清除暂停状态
		{0x00, 0x03, 0x7d, 0x01, 0x00, 0x01, 0xff, 0xff  },//3暂停状态

		{0x00, 0x03, 0x7d, 0x02, 0x00, 0x00, 0xff, 0xff  },//4清除初始化完成状态
		{0x00, 0x03, 0x7d, 0x02, 0x00, 0x01, 0xff, 0xff  },//5初始化完成状态

		{0x00, 0x03, 0x7d, 0x03, 0x00, 0x00, 0xff, 0xff  },//6清除复位完成状态
		{0x00, 0x03, 0x7d, 0x03, 0x00, 0x01, 0xff, 0xff  },//7复位完成状态

		{0x00, 0x03, 0x7d, 0x04, 0x00, 0x00, 0xff, 0xff  },//8清除取标完成状态
		{0x00, 0x03, 0x7d, 0x04, 0x00, 0x01, 0xff, 0xff  },//9取标完成状态


		{0x00, 0x03, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff  },//10清除贴标完成状态
		{0x00, 0x03, 0x7d, 0x05, 0x00, 0x01, 0xff, 0xff  },//11贴标完成状态

		{0x00, 0x03, 0x7d, 0x06, 0x00, 0x00, 0xff, 0xff  },//12清除换料状态
		{0x00, 0x03, 0x7d, 0x06, 0x00, 0x01, 0xff, 0xff  },//13换料状态

		{0x00, 0x03, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff  },//14
		{0x00, 0x03, 0x7d, 0x07, 0x00, 0x01, 0xff, 0xff  },//15

		{0x00, 0x03, 0x7d, 0x08, 0x00, 0x01, 0xff, 0xff  },//16
		{0x00, 0x03, 0x7d, 0x08, 0x00, 0x01, 0xff, 0xff  },//17

		{0x00, 0x03, 0x7d, 0x09, 0x00, 0x00, 0xff, 0xff  },//18 清除请求打印
		{0x00, 0x03, 0x7d, 0x09, 0x00, 0x01, 0xff, 0xff  },//19 请求打印信号

		{0x00, 0x03, 0x7d, 0x0a, 0x00, 0x00, 0xff, 0xff  },//20未报警

		{0x00, 0x03, 0x7d, 0x0a, 0x00, 0x01, 0xff, 0xff  },//21异常报警

		{0x00, 0x03, 0x7d, 0x0b, 0x00, 0x00, 0xff, 0xff  },//22调试模式
		{0x00, 0x03, 0x7d, 0x0b, 0x00, 0x01, 0xff, 0xff  },//23联机模式

		{0x00, 0x03, 0x7d, 0x0c, 0x00, 0x01, 0xff, 0xff  },//24贴标速度保存成功
		{0x00, 0x03, 0x7d, 0x0d, 0x00, 0x01, 0xff, 0xff  },//25贴标位置设置成功
		{0x00, 0x03, 0x7d, 0x0e, 0x00, 0x01, 0xff, 0xff  },//26原点补偿设置成功
		{0x00, 0x03, 0x7d, 0x0f, 0x00, 0x01, 0xff, 0xff  },//27初始化速度设置成功
		{0x00, 0x03, 0x7d, 0x10, 0x00, 0x01, 0xff, 0xff  },//28取标位置设置成功
		{0x00, 0x03, 0x7d, 0x11, 0x00, 0x01, 0xff, 0xff  },//29收料速度保存成功
		{0x00, 0x03, 0x7d, 0x12, 0x00, 0x01, 0xff, 0xff  },//30收料行程保存成功
		{0x00, 0x03, 0x7d, 0x13, 0x00, 0x01, 0xff, 0xff  },//31保压时间保存成功
};


void task(void);
void IO_trigger(void);


int main(void)
{
	SystemCoreClockUpdate();

	delay_ms(1500);

	HAL_NVIC_SetPriorityGrouping(NVIC_PRIORITYGROUP_2);

	MC_config();
	STORAGE_init();

	IBIO_config();
	EXIO_config();

	LED_config();

	QUEUE_init(&recvQueue);
	QUEUE_init(&sendQueue);

	USART2_config();
	USART1_config();

	GUI_initDisplay();

	GUI_switchPageIsolate(32);

	TIM5_config();

	//IWDG_config();

	//EXIO_enableEXI0Interrupt(); //使能中断

	MC_motorStopAllEmergency();

	GUI_showText(0x8000, "        ", 8);
	GUI_showText(0x8000, "0", 1);
	GUI_showTextIsolate(MAINPAGE_MESSAGE_ADDR,MAINPAGE_MESAGE_CLEAR);
	systemPara.RunStatus = 0;
	systemPara.Initstatus = 0;
	systemPara.LackMaterral = 1;

	USART1_sendBuf(sendBuffer[0],8);

	for(;;)
	{
		GUI_handler();

		GUI_sendTask(0);

		task();

		easymodbus_handler();

//		IN_checkMetal();
	}
}

void task(void)
{
	static uint8_t stop_falg = 0;

	IO_trigger();
	StopModeIO(0);

	if(systemPara.isInEmergencyStopEnable)
	{
#if 0
		if(IBIO_getInput(4) == 1)
		{
			stop_falg = 1;
			if(systemPara.Language == 0)
				MAIN_TIPS_WAIT_RST_E_STOP();
			else if(systemPara.Language == 1)
				EN_MAIN_TIPS_WAIT_RST_E_STOP();
			if(EXIO_getOutput(1) == 1)
			{//按下急停输出报警信号
				EXIO_setOutput(1,0);
				GUI_setOutputSignalColorDisp(9,0);
			}
			return;
		}
		else if(IBIO_getInput(4) == 0 && stop_falg == 1)
		{
			stop_falg = 0;
			if(systemPara.Language == 0)
				MAIN_TIPS_RST_E_STOP();
			else if(systemPara.Language == 1)
				EN_MAIN_TIPS_RST_E_STOP();
			if(EXIO_getOutput(1) == 0)
			{
				EXIO_setOutput(1,1);
				GUI_setOutputSignalColorDisp(9,1);
			}
			Clear();//清除所有的标志位
		}
#endif
	}
	

	ChuShiHua(0);
	if(systemPara.Initstatus == 1 && systemPara.AlarmFlag != 3)
	{
		slUpTask_handler(0);
	}
	
	switch(systemPara.status)
	{
	case STATUS_ONLINE:
		
		if(systemPara.Initstatus == 1)
		{
			if(EXIO_getInput(3) == 1)
			{
				Taking(0);
				Labeling(0);
			}
			else
			{
				if(systemPara.Language == 0)
					MAIN_TIPS_EXI_E_STOP();
				else if(systemPara.Language == 1)
					EN_MAIN_TIPS_EXI_E_STOP();
			}
		}
		break;
	case STATUS_AUTO:
		Taking(0);
		Labeling(0);
//		GotoLabelPosi(0);
//		GotoTakePosi(0);
//		GoHome_step(0);
		break;
	case STATUS_FREERUN:
		if(systemPara.Initstatus == 1)
		{
			KongPaoMoShi(0);
		}
		break;
	}

}

void IO_trigger(void)
{
	static uint8_t bSW1flag = 1,bSW2flag = 1,bSW3flag = 1,bSW4flag = 1,bSW5flag = 1;
	static uint8_t RstOK2song = 0;

	if(systemPara.isInEmergencyStopEnable)
	{
		if(IBIO_getInput(4) == 1 && bSW5flag == 1 )
		{//紧急停止触发
			delay_ms(2);
			if(IBIO_getInput(5) == 1)
			{
				bSW5flag = 0;
				systemPara.STOPOnceTriggerByUIorIO = 2;
			}
		}
		if(IBIO_getInput(5) == 0)
		{
			bSW5flag = 1;
		}
	}

	if(EXIO_getInput(2) == 0 && bSW3flag == 1 )
	{//初始化
		delay_ms(5);
		if(EXIO_getInput(2) == 0)
		{
			bSW3flag = 0;
			if(systemPara.isInitSwOnLINEEnable)
			{
				if(systemPara.status != STATUS_ONLINE)
				{
					if(systemPara.Language == 0)
						MAIN_INFO_SW2ONLINE();
					else if(systemPara.Language == 1)
						EN_MAIN_INFO_SW2ONLINE();
					systemPara.status = STATUS_ONLINE;
					AT24CXX_WriteOneByte(STORAGE_WORKMODE_ADDR, systemPara.status);
					GUI_switchModeDisp(systemPara.status);
				}
			}

			if(systemPara.status != STATUS_ONLINE)
			{
				return;
			}

		    if(0)
		    {
				if(systemPara.AlarmFlag == 7 || systemPara.AlarmFlag == 2)
				{
					Vacuum_Action(0, 0);
					delay_ms(100);
					if(IBIO_getInput(4) == 0)
					{
						delay_ms(5);
						if(IBIO_getInput(4) == 0)
						{
							if(systemPara.Language == 0)
								GUI_mainMessageDisp("报警信息：吸盘检测有料，请确认！", 32);
							else if(systemPara.Language == 1)
								GUI_mainMessageDisp("Alarm:Suction plate detection of material, please confirm!", 58);
							EXO_sigOFF(1);
							EXO_sigOFF(2);
							EXO_sigOFF(3);
							EXO_sigOFF(4);
							systemPara.AlarmFlag = 7;
							IBIO_setOutput(1, 1);//关闭真空
							GUI_setOutputSignalColorDisp(0,1);
						}
					}
					Vacuum_Action(1, 0);
				}
				else if(systemPara.AlarmFlag == 3)
				{
					USLflag = 0;
					slUpTask_handler(0);
				}

//				else
				{
					systemPara.AlarmFlag = 0;
					if(systemPara.Language == 0)
						GUI_mainMessageDisp("初始化完成！", 11);
					else
						GUI_mainMessageDisp("Initialization is complete!", 27);
					EXO_sigON(1);
					EXO_sigON(2);
				}
//
//				if(EXIO_getOutput(2) == 0)
//				{
//					systemPara.Err = 0;
//					//EXO_sigOFF(2);//清除报警信号
//				}
		    }
		    else
		    {
		    	systemPara.doInit = 1;
		    }
		}
	}
	if(EXIO_getInput(2) == 1)
	{
		bSW3flag = 1;
	}

	if(systemPara.status != STATUS_ONLINE || systemPara.AlarmFlag != 0)
		return;

	if(EXIO_getInput(3) == 0 && bSW4flag == 1 )
	{//停止触发
		delay_ms(5);
		if(EXIO_getInput(3) == 0)
		{
			bSW4flag = 0;
			systemPara.STOPOnceTriggerByUIorIO = 1;
		}
	}
	if(EXIO_getInput(3) == 1)
	{
		bSW4flag = 1;
	}

	if(systemPara.RunStatus != 0)
		return;
		


	if(systemPara.RunStatus != 0 || !systemPara.Initstatus)
		return;

	if(EXIO_getInput(0) == 0 && bSW1flag == 1)
	{//打印状态-- 收到打印状态，进行接标动作
		delay_ms(5);
		if(EXIO_getInput(0) == 0)
		{
			EXO_sigOFF(2);
			bSW1flag = 0;
			systemPara.doTaking = 1;
		}
	}

	if(EXIO_getInput(0) == 1)
	{
		bSW1flag = 1;
	}

	if(EXIO_getInput(1) == 0 && bSW2flag == 1 )
	{//送标信号
		delay_ms(5);
		if(EXIO_getInput(1) == 0)
		{
			bSW2flag = 0;
			systemPara.doLabeling = 1;
		}
	}

	if(EXIO_getInput(1) == 1)
	{
		bSW2flag = 1;
	}
}



