 /**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f1xx_hal.h"
#include "motorctrl/motorctrl.h"
#include "inboardio/inboardio.h"
#include "exio/exio.h"
#include "at24cxx/at24cxx.h"
#include "storage/storage.h"
#include "delay/delay.h"
#include "tim5/tim5.h"
#include "led/led.h"
#include "dwin/gui.h"
#include "usart2/usart2.h"
#include "queue/queue.h"
#include "paramanager/paramanager.h"
#include "userfunc/userfunc.h"
#include "inputscan/inputscan.h"
#include "usart1/usart1.h"
#include "easymodbus/easymodbus.h"
#include "eventHandler/eventHandler.h"

#include "MdriverAlarmIO/mdriveralarmio.h"

//#include "iwdg/iwdg.h"

void task(void);

#if CONF_FEEDER_VER == 1
	void Auto(void);
#else
	void Auto1(void);
#endif

int main(void)
{
	SystemCoreClockUpdate();

	delay_ms(1500);

	HAL_NVIC_SetPriorityGrouping(NVIC_PRIORITYGROUP_2);

	MC_config();
	STORAGE_init();

	IBIO_config();
	EXIO_config();

	LED_config();

	QUEUE_init(&recvQueue);
	QUEUE_init(&sendQueue);

	USART2_config();
	USART1_config();

	//systemPara.Language = 0;//默认中文，用于中文触摸屏

	GUI_initDisplay();

	GUI_switchPageIsolate(32);
	systemPara.Page = 0;

	TIM5_config();

	//IWDG_config();

	MC_motorStopAllEmergency();

	GUI_showText(0x8000, "        ", 8);
	GUI_showText(0x8000, "0", 1);
//	systemPara.logginStatus = 12;
	systemPara.RunStatus = 0;
	systemPara.Initstatus = 0;
	systemPara.LackMaterral = 1;
	USART1_sendBuf(sendBuffer[1],8);

	for(;;)
	{
		GUI_handler();

		GUI_sendTask(0);

		task();

		easymodbus_handler();
		Platform_signal_detection();
		//驱动器报警检测
		if(MDAIO_getInput(0,1) == 0)
		{
			M0driveALM();
		}
		if(MDAIO_getInput(1,1) == 0)
		{
			M2driveALM();
		}
	}
}

void task(void)
{
	static uint8_t stop_falg = 0,stop_falg1 = 0;

	StopModeIO(0);

#if CONF_FEEDER_VER == 1
		Auto();
#else
		Auto1();
#endif

	if(systemPara.isInEmergencyStopEnable)
	{
		if(IBIO_getInput(12) == 1)
		{
			stop_falg = 1;
			if(systemPara.Language == 0)
				MAIN_TIPS_WAIT_RST_E_STOP();
			else if(systemPara.Language == 1)
				EN_MAIN_TIPS_WAIT_RST_E_STOP();
			//关闭交互信号
			EXO_sigOFF(1);
			EXO_sigOFF(2);
			EXO_sigOFF(3);
			EXO_sigOFF(4);
			EXO_sigOFF(5);
			return;
		}
		else if(IBIO_getInput(12) == 0 && stop_falg == 1)
		{
			delay_ms(2);
			if(IBIO_getInput(12) == 0)
			{
				stop_falg = 0;
				if(systemPara.Language == 0)
					MAIN_TIPS_RST_E_STOP();
				else if(systemPara.Language == 1)
					EN_MAIN_TIPS_RST_E_STOP();
				Clear();//清除所有的标志位
			}
		}
	}
	if(systemPara.status == STATUS_ONLINE)
	{
		if(EXIO_getInput(3) == 0)
		{
			delay_ms(5);
			if(EXIO_getInput(3) == 0)
			{
				stop_falg1 = 1;
				if(systemPara.Language == 0)
					MAIN_TIPS_EXI_E_STOP();
				else if(systemPara.Language == 1)
					EN_MAIN_TIPS_EXI_E_STOP();
				//关闭交互信号
				EXO_sigOFF(1);
				EXO_sigOFF(2);
				EXO_sigOFF(3);
				EXO_sigOFF(4);
				EXO_sigOFF(5);
				return;
			}
		}
		else if(EXIO_getInput(3) == 1 && stop_falg1 == 1)
		{
			stop_falg1 = 0;
			if(systemPara.Language == 0)
				MAIN_TIPS_RST_EXI_E_STOP();
			else if(systemPara.Language == 1)
				EN_MAIN_TIPS_RST_EXI_E_STOP();
			Clear();//清除所有的标志位
		}
	}
	ChuShiHua(0);
	AddMetal_task();
	if(systemPara.Initstatus == 1)
	{
		if(systemPara.isUpShouSensorEnable != 0)
			UpslTask_handler(0);
#if CONF_LET_VER == 1
		flTask_handler(0);
#else

		if(systemPara.isDownShouSensorEnable != 0)
			DownslTask_handler(0);
#endif
	}

	switch(systemPara.status)
	{
	case STATUS_ONLINE://联机生产模式
		if(systemPara.Initstatus == 1)
		{
//			if(EXIO_getInput(3) == 1 )
			{
				if(systemPara.RunStatus != 1)
					GoHome_step(0);
				BoliaoHC_Step_IO(0);
				BoliaoRST_Step_IO(0);

				if(systemPara.isRSTAutoSongEnable && EXIO_getInput(1)==0 && motor_ch[BO_MOTOR].status != Motor_Stop)
				{//同步复位送料,复位未完成
					systemPara.givenOnceTriggerByUIorIO = 0;
					return;
				}
				else {
					GivenMatieralOnline(0);
				}
				IN_checkMetal();
			}
//			else
//			{
//				if(systemPara.Language == 0)
//					MAIN_TIPS_EXI_E_STOP();
//				else if(systemPara.Language == 1)
//					EN_MAIN_TIPS_EXI_E_STOP();
//			}
		}
		break;
	case STATUS_AUTO://调试模式
		GivenMatieralOnline(0);
		BoliaoHC_Step_IO(0);
		BoliaoRST_Step_IO(0);
		BoliaoHCRST_Step_IO(0);
		if(systemPara.RunStatus != 1)
			GoHome_step(0);

#if CONF_BLRST_VER == 1
		if(systemPara.RSTOnceOK  && Rst2Feedflag == 1)
		{//复位触发
			Rst2Feedflag = 0;
			systemPara.givenOnceTriggerByUIorIO = 1;
		}
#endif

		if(systemPara.Page != 4 && ( !(EXIO_getOutput(0)) || !(EXIO_getOutput(1)) || !(EXIO_getOutput(2)) || !(EXIO_getOutput(3)) || !(EXIO_getOutput(4)) ))
		{//输出页面不关闭，方便信号对接
			EXO_sigOFF(1);
			EXO_sigOFF(2);
			EXO_sigOFF(3);
			systemPara.Err = 1;
			EXO_sigOFF(4);
			EXO_sigOFF(5);
		}
		break;
	case STATUS_FREERUN://空跑老化
		if(systemPara.Initstatus == 1)
		{
			KongPaoMoShi(0);
			BoliaoHC_Step_IO(0);
			BoliaoRST_Step_IO(0);
		}
		break;
	}
}

#if CONF_FEEDER_VER == 1
void Auto(void) //按键板外部输入检测
{
	static uint8_t bSW1flag = 1,bSW2flag = 1,bSW3flag = 1,bSW4flag = 1,bSW5flag = 1;
	static uint16_t count = 0;

	if(systemPara.isInEmergencyStopEnable)
	{
		if(IBIO_getInput(12) == 1 && bSW5flag == 1 )
		{//紧急停止触发
			delay_ms(2);
			if(IBIO_getInput(12) == 1)
			{
				bSW5flag = 0;
				systemPara.STOPOnceTriggerByUIorIO = 2;
			}
		}
		if(IBIO_getInput(12) == 0)
		{

			bSW5flag = 1;
		}
	}

	if(EXIO_getInput(2) == 0 && bSW3flag == 1 )
	{//初始化触发
		delay_ms(10);
		if(EXIO_getInput(2) == 0)
		{
			bSW3flag = 0;
			if(systemPara.isInitSwOnLINEEnable && systemPara.status != STATUS_ONLINE)
			{
				if(systemPara.Language == 0)
					MAIN_INFO_SW2ONLINE();
				else if(systemPara.Language == 1)
					EN_MAIN_INFO_SW2ONLINE();
				systemPara.status = STATUS_ONLINE;
				AT24CXX_WriteOneByte(STORAGE_WORKMODE_ADDR, systemPara.status);
				GUI_switchModeDisp(systemPara.status);

				if(!IBIO_getInput(1) && systemPara.Initstatus == 1)
				{
					if(systemPara.givenOnceOK == 1)
#if CONF_Fiber_VER == 0
						EXO_sigON(2);
#endif
						EXO_sigON(3);
						EXO_sigON(5);
				}
			}

			if(systemPara.status != STATUS_ONLINE)
			{
				return;
			}

			if(!(EXIO_getOutput(1)))
			{
				systemPara.Err = 0;
				EXO_sigOFF(4);//清除报警信号
			}
			if(systemPara.Initstatus == 0)
			{
				systemPara.doInit = 1;
			}
		}
	}
	if(EXIO_getInput(2) == 1)
	{
		bSW3flag = 1;
	}

	if(systemPara.status != STATUS_ONLINE)
		return;

	if(EXIO_getInput(3) == 0 && bSW4flag == 1 )
	{//停止触发
		delay_ms(5);
		if(EXIO_getInput(3) == 0)
		{
			bSW4flag = 0;
			systemPara.STOPOnceTriggerByUIorIO = 1;
		}
	}
	if(EXIO_getInput(3) == 1)
	{
		bSW4flag = 1;
	}

	if(systemPara.Initstatus == 0 && systemPara.RunStatus != 0)
		return;

	if(systemPara.isRSTAutoSongEnable == 0)
	{//未开启自动复位同步送料
//		if(systemPara.RunStatus != 0)
//		{
//			return;
//		}

		if(systemPara.isAutoSongEnable == 1 && systemPara.HCOnceTriggerByUIorIO == 0 && motor_ch[BO_MOTOR].status == Motor_Stop  )
		{//自动送料
#if CONF_Fiber_VER == 0
			if(IBIO_getInput(2) && systemPara.RSTOnceOK)
			{
				delay_ms(10);
				if(IBIO_getInput(2))
#else
			if((IBIO_getInput(2) && IBIO_getInput(3)) && systemPara.RSTOnceOK)
			{
				delay_ms(10);
				if(IBIO_getInput(2) && IBIO_getInput(3))
#endif
				{
					if(systemPara.Language == 0)
						GUI_mainMessageDisp("自动送料中...", 13);
					else if(systemPara.Language == 1)
						GUI_mainMessageDisp("Automatic feeding...", 20);

					systemPara.givenOnceTriggerByUIorIO = systemPara.sensorChosen;
				}
			}
		}
		else
		{
			if(!EXIO_getInput(0) && bSW1flag == 1)
			{//外部触发送料
				delay_ms(10);
#if CONF_BLRST_VER == 0
				if(systemPara.RSTOnceOK)
#endif
				{
					if(!EXIO_getInput(0))
					{
						bSW1flag = 0;
#if CONF_BLRST_VER == 1
						if(systemPara.HCOnceOK && EXIO_getInput(1) )
						{//复位触发
							delay_ms(5);
							if(EXIO_getInput(1))
							{
								Rst2Feedflag = 1;
								systemPara.RSTOnceTriggerByUIorIO = 1;
								return;
							}
						}
#endif
						systemPara.givenOnceTriggerByUIorIO = systemPara.sensorChosen;
					}
				}
#if CONF_BLRST_VER == 0
				else
				{
					if(systemPara.Language == 0)
						GUI_mainMessageDisp("请先复位！", 10);
					else if(systemPara.Language == 1)
						GUI_mainMessageDisp("Please reset first.", 19);
				}
#endif
			}

#if CONF_BLRST_VER == 1
		if(systemPara.RSTOnceOK == 1 && Rst2Feedflag == 1)
		{//复位触发
			Rst2Feedflag = 0;
			systemPara.givenOnceTriggerByUIorIO = 1;
		}
#endif
			if(EXIO_getInput(0) == 1)
			{
				bSW1flag = 1;
			}
		}
#if CONF_BLRST_VER == 0
		if(systemPara.HCOnceOK && EXIO_getInput(1) )
		{//复位触发
			delay_ms(10);
			if(EXIO_getInput(1))
			{
				systemPara.RSTOnceTriggerByUIorIO = 1;
			}
		}
#endif
	}
	else//开启自动复位同步送料
	{
#if CONF_Fiber_VER == 0
		if(!systemPara.givenOnceTriggerByUIorIO && IBIO_getInput(2) && (systemPara.RSTOnceOK || systemPara.RunStatus == 4))
#else
		if(!systemPara.givenOnceTriggerByUIorIO && IBIO_getInput(2) && IBIO_getInput(3) && (systemPara.RSTOnceOK || systemPara.RunStatus == 4))
#endif
		{//初始化后自动送料
			delay_ms(10);
			if(++count >= 10)
			{
				count = 0;
#if CONF_Fiber_VER == 0
				if(IBIO_getInput(2))
#else
				if(IBIO_getInput(2) && IBIO_getInput(3))
#endif
				{
					if(systemPara.Language == 0)
						GUI_mainMessageDisp("自动送料中...", 13);
					else if(systemPara.Language == 1)
						GUI_mainMessageDisp("Automatic feeding...", 20);

					systemPara.givenOnceTriggerByUIorIO = systemPara.sensorChosen;
				}
			}
		}

		if(!systemPara.RSTOnceTriggerByUIorIO && (systemPara.HCOnceOK || systemPara.HCTwoOK) && EXIO_getInput(1))
		{//剥料完成自动复位
			delay_ms(10);
			if(EXIO_getInput(1))
//				GUI_mainMessageDisp("自动复位中...", 13);
			systemPara.RSTOnceTriggerByUIorIO = 1;
		}
	}

	if(motor_ch[GIVEN_MOTOR].status == Motor_Stop && !systemPara.HCOnceOK && !EXIO_getInput(1) && bSW2flag == 1 )
	{//后撤触发
		delay_ms(10);
		if(!EXIO_getInput(1))
		{
			if(!systemPara.isCloseHCEnable)
			{
				if(controlPara.boDistance > 0)
				{
					bSW2flag = 0;
					systemPara.HCOnceTriggerByUIorIO = 1;
				}
				else
				{
					if(systemPara.Language == 0)
						GUI_mainMessageDisp("提示信息：后撤行程1未设置！", 27);
					else if(systemPara.Language == 1)
						GUI_mainMessageDisp("Tip: Retreat stroke 1 is not set!", 33);
				}
			}
			else
			{
				if(systemPara.Language == 0)
					GUI_mainMessageDisp("后撤功能已屏蔽！", 16);//
				else if(systemPara.Language == 1)
					GUI_mainMessageDisp("Back function is not enabled.", 29);
			}
		}
	}

	if(EXIO_getInput(1) == 1)
	{
		bSW2flag = 1;
	}
}
#else
void Auto1(void)
{
	static uint8_t bSW1flag = 1,bSW2flag = 1,bSW3flag = 1,bSW4flag = 1;

	if(EXIO_getInput(0) == 0 && bSW3flag == 1 )
	{//初始化触发
		delay_ms(20);
		if(EXIO_getInput(0) == 0)
		{
			if(!(EXIO_getOutput(1)))
			{
				bSW3flag = 0;
				systemPara.Err = 0;
				EXO_sigOFF(4);//清除报警信号
			}
			if(systemPara.Initstatus == 0)
			{
				bSW3flag = 0;
				systemPara.doInit = 1;
			}
		}
	}
	if(EXIO_getInput(0) == 1)
	{
		bSW3flag = 1;
	}

//	if(EXIO_getInput(3) == 0 && bSW4flag == 1 )
//	{//停止触发
//		delay_ms(10);
//		if(EXIO_getInput(3) == 0)
//		{
//			bSW4flag = 0;
//			systemPara.STOPOnceTriggerByUIorIO = 1;
//		}
//	}
//	if(EXIO_getInput(3) == 1)
//	{
//		bSW4flag = 1;
//	}

	if(systemPara.Initstatus == 1)
	{
		if(systemPara.isRSTAutoSongEnable == 0)
		{//未开启自动复位同步送料
			if(systemPara.RunStatus != 0)
			{
				return;
			}

			if(systemPara.isAutoSongEnable == 1 )
			{//自动送料

#if CONF_Fiber_VER == 0
				if(IBIO_getInput(2) == 1 && IBIO_getInput(1) == 0)
				{
					delay_ms(10);
					if(IBIO_getInput(2) == 1
#else
				if(IBIO_getInput(2) == 1 && IBIO_getInput(3) == 1 && IBIO_getInput(1) == 0)
				{
					delay_ms(10);
					if(IBIO_getInput(2) == 1 &&I BIO_getInput(3) == 1 )
#endif
					{
						if(systemPara.Language == 0)
							GUI_mainMessageDisp("自动送料中...", 13);
						else if(systemPara.Language == 1)
							GUI_mainMessageDisp("Automatic feeding...", 20);
						systemPara.givenOnceTriggerByUIorIO = 1;
					}
				}
			}
			else
			{
				if(EXIO_getInput(1) == 0 && bSW1flag == 1)
				{//外部触发送料
					delay_ms(20);
					if(IBIO_getInput(1) == 0)
					{
						if(EXIO_getInput(1) == 0)
						{
							bSW1flag = 0;
							if(systemPara.sensorChosen == 1)
							{//下光纤模式
								systemPara.givenOnceTriggerByUIorIO = 1;
							}
							else
							{//上光纤模式
								systemPara.givenOnceTriggerByUIorIO = 2;
							}
						}
					}
					else
					{
						if(systemPara.Language == 0)
							GUI_mainMessageDisp("请先复位！", 10);
						else if(systemPara.Language == 1)
							GUI_mainMessageDisp("Please reset first.", 19);
					}
				}
				else
				{
					systemPara.givenOnceTriggerByUIorIO = 0;
				}

				if(EXIO_getInput(1) == 1)
				{
					bSW1flag = 1;
				}

			}

			if(systemPara.HCOnceOK == 1 && EXIO_getInput(2) == 1 )
			{//复位触发
				delay_ms(20);
				if(EXIO_getInput(2) == 1 )
				{
					systemPara.RSTOnceTriggerByUIorIO = 1;
				}
			}
		}
		else//开启自动复位同步送料
		{
#if CONF_Fiber_VER == 0
		if(IBIO_getInput(2) == 1)
		{
			delay_ms(5);
			if(IBIO_getInput(2) == 1)
			{
				if(IBIO_getInput(1) == 0  && systemPara.givenOnceTriggerByUIorIO == 0)
				{//初始化后自动送料
					delay_ms(10);
					if(IBIO_getInput(2) == 1)
#else
		if(IBIO_getInput(2) == 1 && IBIO_getInput(3) == 1)
		{
			delay_ms(10);
			if(IBIO_getInput(2) == 1 && IBIO_getInput(3) == 1)
			{
				if(IBIO_getInput(1) == 0  && systemPara.givenOnceTriggerByUIorIO == 0)
				{//初始化后自动送料
					delay_ms(10);
					if(IBIO_getInput(2) == 1 && IBIO_getInput(3) == 1 )
#endif

						{
							if(systemPara.Language == 0)
								GUI_mainMessageDisp("自动送料中...", 13);
							else if(systemPara.Language == 1)
								GUI_mainMessageDisp("Automatic feeding...", 20);
							systemPara.givenOnceTriggerByUIorIO = 1;
						}
					}

					if(systemPara.HCOnceOK == 1 && systemPara.HCTwoOK == 0)//剥料完成自动复位
					{
#if CONF_Fiber_VER == 0
						if(IBIO_getInput(2) == 1 )
						{//复位后自动送料
							delay_ms(10);
							if(IBIO_getInput(2) == 1)
#else
						if(IBIO_getInput(2) == 1 && IBIO_getInput(3) == 1)
						{
							delay_ms(10);
							if(IBIO_getInput(2) == 1 && IBIO_getInput(3) == 1)
							{
#endif
							{
								GUI_mainMessageDisp("自动复位中...", 13);
								systemPara.RSTOnceTriggerByUIorIO = 1;
							}
						}
					}
					else if(systemPara.HCOnceOK == 1 && systemPara.HCTwoOK == 1 && EXIO_getInput(2) == 1 )
					{//2次剥料完成
						delay_ms(20);
						if(EXIO_getInput(2) == 1 )
						{
							systemPara.RSTOnceTriggerByUIorIO = 1;
						}
					}
					//等待剥料复位开始后，再进行送料
					if(systemPara.RunStatus == 4)
						systemPara.givenOnceTriggerByUIorIO = 1;
				}
			}
		}

		if(systemPara.HCOnceOK == 0 && EXIO_getInput(2) == 0 && bSW2flag == 1 )
		{//后撤触发
			delay_ms(20);
			if(EXIO_getInput(2) == 0)
			{
				if(systemPara.RunStatus == 0)
				{
					if(controlPara.boDistance > 0)
					{
						bSW2flag = 0;
						systemPara.HCOnceTriggerByUIorIO = 1;
					}
					else
					{
						//GUI_mainMessageDisp("提示信息：后撤行程1未设置！", 27);
					}
				}
				else if(systemPara.RunStatus == 2)
				{
					//GUI_mainMessageDisp("提示信息：送料进行中！", 22);
				}
			}
		}

		if(EXIO_getInput(2) == 1)
		{
			bSW2flag = 1;
		}
	}
}
#endif

